Pws1 39 historia component
ScrumLatamCommunity/web-portal pull request #44
Opened 2024-11-30 00:03 UTC by GabTorres17

## Feature o Ticket

- Jira/Trello/Toro Link: PWS1-39 History-Mision-Vision

## Descripción

Breve descripción: Implementación del componente MisionVision que muestra de manera dinámica la misión, visión y otros elementos históricos de la organización. Este componente es completamente responsivo y está optimizado para diferentes tamaños de pantalla.

Detalles:

-Se añadieron nuevos componentes DesktopMisionVision y MobileMisionVision para mostrar información dinámica proveniente de la estructura history.
- Se actualizaron los estilos utilizando Tailwind CSS y implementando Tailwind Scrollbar para mejorar la UI/UX, incluyendo diseño responsivo.

## ¿Cómo se ha probado esto?

Se realizaron pruebas en las siguientes vistas para asegurar que los cambios funcionen correctamente:

Test 1: Verifica que los datos provenientes de la estructura history se muestren correctamente, incluyendo título, descripción e imágenes.
Test 2: Asegura que el componente se renderice sin errores relacionados con claves (key) en los elementos listados.
Test 3: Comprueba que el diseño sea responsivo al reducir o aumentar el tamaño de la ventana.

### Pasos para reproducir:

1. Navegar a la vista DesktopMisionVision y MobileMisionVision.
2. Verificar que los elementos del componente (imágenes, títulos y descripciones) se muestren correctamente.
3. Reducir el tamaño de la ventana del navegador para comprobar que el diseño responsivo está funcionando.

2024-11-30 01:33 UTC, neriheredia requested changes

2024-11-30 01:33 UTC, neriheredia commented on src/app/history/components/MobileMisionVision.tsx
> +          >
Orden alfabetico

2024-12-01 16:01 UTC, GabTorres17 commented on src/app/history/components/MobileMisionVision.tsx
> +          >
Arreglado, gracias por el feedback!

2024-12-05 15:36 UTC, neriheredia approved these changes

2024-12-05 15:37 UTC, merged