Pws1 10 login register
ScrumLatamCommunity/web-portal pull request #45
Opened 2024-12-01 03:46 UTC by aljodavid10

## Feature o Ticket

- Jira Link: [Alejo Botón de Iniciar Sesión y Registrate](https://scrumlatamc.atlassian.net/browse/PWS1-10?atlOrigin=eyJpIjoiOTNjMjY1YTZlN2M4NGQyZjliNjI2MzNkNmJjMTNiMTIiLCJwIjoiaiJ9)

## Descripción

**Breve descripción:** Se implementó la funcionalidad para redirigir a las vistas de "Inicio de sesión" y "Registro" desde la barra de navegación y creando sus respectivos componenetes. 

**Detalles:**

- Se actualizó la barra de navegación (`Navbar`) para usar el componente `Link` en lugar de los enlaces `<a>`, permitiendo una navegación eficiente y sin recarga de la página.
- Se crearon los componentes `Login` y `Register`, con sus respectivas vistas y lógica asociada.
- Se actualizaron los estilos de la barra de navegación para asegurar una buena experiencia de usuario.
- Validación de rutas asegurada para las páginas de inicio de sesión y registro.

## ¿Cómo se ha probado esto?

Se realizaron pruebas en las siguientes vistas para asegurar que los cambios funcionen correctamente:

- **Vista `Navbar`:**
  - **Test 1:** Verifica que al hacer clic en el botón "Iniciar sesión" se redirige correctamente a la vista de login.
  - **Test 2:** Asegura que al hacer clic en el botón "Registrarse" se redirige correctamente a la vista de registro.
  
- **Vista `Login`:**
  - **Test 1:** Comprueba que los campos de formulario se muestran correctamente y que las validaciones funcionan.
  
- **Vista `Register`:**
  - **Test 1:** Asegura que el formulario de registro se muestra correctamente y que los datos se manejan de forma adecuada.

### Pasos para reproducir:

1. Navegar a la página principal donde está ubicada la barra de navegación (`Navbar`).
2. Hacer clic en el botón "Iniciar sesión" o "Registrarse".
3. Verificar que se redirige correctamente a las vistas de login o registro, respectivamente.

2024-12-05 22:50 UTC, neriheredia requested changes

2024-12-05 22:50 UTC, neriheredia commented on src/app/login/components/LoginForm.tsx
> +        />
Orden alfabetico

2024-12-05 22:50 UTC, neriheredia commented on src/app/login/components/LoginForm.tsx
> +        />
Orden alfabetico

2024-12-05 22:50 UTC, neriheredia commented on src/app/login/components/LoginForm.tsx
> +      </button>
Igual aquí

2024-12-05 22:50 UTC, neriheredia commented on src/app/register/components/RegisterComponent.tsx
> +            />
Igual aquí

2024-12-05 22:50 UTC, neriheredia commented on src/app/register/components/RegisterComponent.tsx
> +            />
Orden alfabetico

2024-12-05 22:50 UTC, neriheredia commented on src/app/register/components/RegisterComponent.tsx
> +            />
Igual aquí

2024-12-05 22:50 UTC, neriheredia commented on src/app/register/components/RegisterComponent.tsx
> +            />
Igual aquí

2024-12-05 22:50 UTC, neriheredia commented on src/app/register/components/RegisterComponent.tsx
> +          >
igual aquí

2024-12-09 22:13 UTC, aljodavid10 commented on src/app/login/components/LoginForm.tsx
> +        />
Resuelto en el ultimo commit

2024-12-09 22:13 UTC, aljodavid10 commented on src/app/login/components/LoginForm.tsx
> +      </button>
Resuelto en el ultimo commit

2024-12-09 22:13 UTC, aljodavid10 commented on src/app/register/components/RegisterComponent.tsx
> +            />
Resuelto en el ultimo commit

2024-12-09 22:13 UTC, aljodavid10 commented on src/app/register/components/RegisterComponent.tsx
> +            />
Resuelto en el ultimo commit

2024-12-09 22:13 UTC, aljodavid10 commented on src/app/register/components/RegisterComponent.tsx
> +            />
Resuelto en el ultimo commit

2024-12-09 22:14 UTC, aljodavid10 commented on src/app/register/components/RegisterComponent.tsx
> +            />
Resuelto en el ultimo commit

2024-12-09 22:14 UTC, aljodavid10 commented on src/app/register/components/RegisterComponent.tsx
> +          >
Resuelto en el ultimo commit

2024-12-10 11:07 UTC, neriheredia approved these changes

2024-12-10 11:08 UTC, merged