Pws1 69 desplegables submenús navbar
ScrumLatamCommunity/web-portal pull request #47
Opened 2024-12-02 20:53 UTC by aljodavid10

## Feature o Ticket

- Jira/Trello/Toro Link: Nombre del ticket o feature

## Descripción

Breve descripción: Implementación de la funcionalidad para [describir la tarea realizada]. Se añadió la vista para [nombre de la vista], se integraron las APIs necesarias y se realizaron las validaciones correspondientes en el frontend.

Detalles:

- Se añadió un nuevo componente NombreDelComponente para [descripción de lo que hace el componente].
- Se actualizaron los estilos utilizando [framework o librería de estilos] para mejorar la UI/UX.
- Integración con el backend para [descripción de la integración].
- Validaciones añadidas para [explicar cualquier validación nueva].
- Refactorización de [cualquier código relevante] para [motivo del refactor].

## ¿Cómo se ha probado esto?

Se realizaron pruebas en las siguientes vistas para asegurar que los cambios funcionen correctamente:

- Vista A: [Descripción de la vista afectada]
  - Test A1: Verifica que [descripción del test]
  - Test A2: Asegura que [descripción del test]
- Vista B: [Descripción de la vista afectada]
  - Test B1: Comprueba que [descripción del test]
  - Test B2: Asegura que [descripción del test]

### Pasos para reproducir:

1. Navegar a la vista [Nombre de la vista].
2. Ejecutar la acción [Acción específica, como "hacer clic en el botón X"].
3. Verificar que [lo que debería suceder, como "la nueva información se muestra correctamente"].

### Notas adicionales:

Si corresponde, mencionar cualquier ajuste en la configuración o en los archivos de entorno necesarios para que los cambios funcionen.
Mencionar cualquier dependencia nueva que se haya añadido al proyecto.

**Nota:** **_Borrar los textos y ejemplos, dejar solo lo que se utilizo._**

2024-12-05 22:53 UTC, neriheredia requested changes

2024-12-05 22:53 UTC, neriheredia commented on src/app/login/components/LoginForm.tsx
> +        />
Orden alfabetico

2024-12-05 22:53 UTC, neriheredia commented on src/app/login/components/LoginForm.tsx
> +        />
Orden alfabetico

2024-12-05 22:53 UTC, neriheredia commented on src/app/login/components/LoginForm.tsx
> +      >
Igual aquí

2024-12-05 22:53 UTC, neriheredia commented on src/app/register/components/RegisterComponent.tsx
> +            />
Aquí también

2024-12-05 22:53 UTC, neriheredia commented on src/app/register/components/RegisterComponent.tsx
> +            />
Aquí igual

2024-12-05 22:53 UTC, neriheredia commented on src/app/register/components/RegisterComponent.tsx
> +            />
Igual aquí

2024-12-05 22:53 UTC, neriheredia commented on src/app/register/components/RegisterComponent.tsx
> +          >
Aquí también

2024-12-10 18:13 UTC, aljodavid10 commented on src/app/login/components/LoginForm.tsx
> +        />
corregido en el ultimo commit

2024-12-10 18:13 UTC, aljodavid10 commented on src/app/login/components/LoginForm.tsx
> +      >
corregido en el ultimo commit

2024-12-10 18:14 UTC, aljodavid10 commented on src/app/register/components/RegisterComponent.tsx
> +            />
corregido en el ultimo commit

2024-12-10 18:14 UTC, aljodavid10 commented on src/app/register/components/RegisterComponent.tsx
> +            />
corregido en el ultimo commit

2024-12-10 18:14 UTC, aljodavid10 commented on src/app/register/components/RegisterComponent.tsx
> +            />
corregido en el ultimo commit

2024-12-10 18:14 UTC, aljodavid10 commented on src/app/register/components/RegisterComponent.tsx
> +          >
corregido en el ultimo commit

2024-12-20 17:34 UTC, neriheredia submitted a review, later dismissed

2024-12-20 17:37 UTC, merged